name: Publish to GitHub Packages

on:
  push:
    branches: ["main"]
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/acestream-link-scraper

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/acestream-link-scraper:latest
            ghcr.io/${{ github.repository_owner }}/acestream-link-scraper:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/acestream-link-scraper:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Push git tag
        if: github.event_name == 'release'
        run: git push origin ${{ github.ref }}

      - name: Notify on failure
        if: failure()
        run: |
          echo "Build failed. Check the logs."
